spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/montysinha7/eks-blueprints-workloads
    targetRevision: main
  ingress:
    host: dev.example.com
